-- Your SQL goes here
DROP TABLE IF EXISTS `outbound_statistics`;
CREATE TABLE `outbound_statistics`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sap_no` int(11) NOT NULL,
  `out_type`  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `out_category` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `deliver_year` int(11),
      `mark_month` int(11),
      `out_month` int(11),
      `out_date` DATETIME,
      `province` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
      `county` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `area` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `area_level` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `bus_owner` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
      `customer_name` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `product_name` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `package_form` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `specifications` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
      `out_num` int(11) ,
      `single_price` int(11) ,
      `sale_num` int(11) ,
      `out_no` int(11) ,
      `deliver_no` int(11),
      `comment` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `batch_no` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `dead_line` DateTime,
      `return_label` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `invoice_pass` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `invoice_type` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `invoice_count`  int(11) ,
      `promoter_company_name`varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `foregin_money` int(11) ,
      `crm_client_code` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `pass_one` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `pass_two` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `pass_unit` varchar(255) CHARACTER  SET utf8mb4 COLLATE utf8mb4_general_ci,
      `out_num_discount` int(11) ,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;
SET FOREIGN_KEY_CHECKS = 1;